name: on-push
on:
  push:
    branches: [main]
    paths:
      - 'packages/tidier-lib/**/*'
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - run: yarn
      - run: yarn build:lib
      - run: yarn build:test
      - run: yarn test:lib
      - run: yarn release:lib
